### PR TITLE
Improves ERA5 download script

### PR DESCRIPTION
**Pull request by glwagner**
The request is running...

```
(base) ~/Projects/covid-environmental-factors/scripts$ python download_era5_temperature_dewpoint_pressure.py 
2020-03-27 07:57:28,215 INFO Welcome to the CDS
2020-03-27 07:57:28,215 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels
2020-03-27 07:57:28,670 INFO Request is queued
2020-03-27 07:57:29,761 INFO Request is running
```

But that's all I got so far.

@hdrake (or others) let me know if this works for you. Happy to fix it up more too.

### CODE REVIEW

**Review by hdrake — COMMENTED** [review]
Any reason we're sampling every two hours? Just to make the data request half as big? Are we sure we want to effectively get rid of half of the dataset?

**Comment by hdrake** [comment]
> But that's all I got so far.

Did it go through?

**Comment by glwagner** [comment]
> Did it go through?

Yes!

> Any reason we're sampling every two hours? Just to make the data request half as big? Are we sure we want to effectively get rid of half of the dataset?

Yes, the purpose of reduced sampling is to reduce the size of the data request. I'm happy to to back to sampling every hour. We can split the requests up by month.

Earlier I had trouble writing a loop over the requests, but that's a bad excuse for not breaking the requests up :-/

Let me know what you think, happy to make changes.

**Comment by glwagner** [comment]
By the way, should we move these scripts into the `/data` folder? We will probably have lots of scripts, not all of them related to downloading data.

**Comment by glwagner** [comment]
@hdrake ok, I split the downloads by month and ask for hourly data. I'm not sure if my python skills failed me but I was forced to copy/paste the requests. Anyways, I guess it works for now.

**Comment by hdrake** [comment]
This is great, thanks Greg!

**Review by hdrake — APPROVED** [review]
This is great for now. Eventually we'll probably want to clean this up & update the months so that we get April 2020 data!

**Pull request merged**
